### ISSUE TITLE
I want to help on this project!

### ISSUE THREAD

**Issue by parinzee** [i3-gnome/i3-gnome#100]
Hello! I hope you're having a great day! 

My name is Parin and I believe I could help out on this project regarding its documentation, website ([i3-gnome.github.io](https://github.com/i3-gnome/i3-gnome.github.io)) and the project itself!

For context, I'm a Linux Enthusiast as well as a programmer. You can check my [Github](https://github.com/parinzee) to see some of my projects. Although these projects are opensource, I feel that I haven't really contributed a huge deal to tools that people use; I think this project would help me get started with actually contributing to open-source! Besides, I use i3-gnome on a daily basis and I want to give back to the community!

Sincerely,
Parin

**Comment by jcstr** [comment]
Hey @parinzee! I'm sorry for the delated answer.

Thanks for your interest on the project it will be really cool to have you here with us.

You're more than welcome.
