### ISSUE TITLE
I want to help on this project!

### ISSUE THREAD

**Issue by EidolonForgery** [i3-gnome/i3-gnome#101]
I'm looking to help out in the FOSS community and i3 is something I *really* enjoy using. I'm happy to help out, especially with documentation. I frequently use Arch, but also have extensive experience with Debian and Ubuntu and can help out wherever it's needed!

**Comment by jcstr** [comment]
hey @EidolonForgery! Thanks for dropping by. I'm sorry for the delayed answer.

It's really cool that you want to help on i3-gnome.

You're more than welcome.
