### ISSUE TITLE
Bluetooth notifications spawn in middle of screen and don't go away

### ISSUE THREAD

**Issue by nathan-barry** [i3-gnome/i3-gnome#105]
**Describe the bug**
When a bluetooth device is connected, the notification spawns in the center of the screen and doesn't go away naturally

**To Reproduce**
Connect or disconnect  a bluetooth device

**Expected behavior**
Notifications appear in top right and disappear after a few seconds

**Screenshots**
![screenshot_20220819_114911](https://user-images.githubusercontent.com/38043930/185668545-1ce791c5-147c-40c1-8a11-41a383fa8c26.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by 0xnathanbarry** [comment]
Any quick solutions for this? I'm using i3-gnome since I'm using this on a laptop and for some reason, with normal i3, it just doesn't detect the laptop screen when you open it 20% of the time.

**Comment by 0xnathanbarry** [comment]
Also the notifications spawn dead center. I just moved them around a bit to show that they just don't disappear but normally they stack up ontop of eachother so you can't tell how many are actually there
