### ISSUE TITLE
Unable to open GNOME Settings

### ISSUE THREAD

**Issue by mmstick** [i3-gnome/i3-gnome#36]
With GNOME 3.32, GNOME Settings immediately segfaults

**Comment by gammons** [comment]
I'm getting the same issue.  And in fact, I cannot even start a gnome-flashback session from GDM.  This is probably not an i3-gnome issue, but it will probably affect anyone using an updated arch right now.

The error I am getting is this:

```
gnome-flashback[29507]: Settings schema 'org.gnome.desktop.peripherals.touchscreen' does not contain a key named 'display'
systemd-coredump[29649]: Process 29507 (gnome-flashback) of user 1000 dumped core.

                                                      Stack trace of thread 29507:
                                                      #0  0x00007f8eb1bed4e6 n/a (libglib-2.0.so.0)
                                                      #1  0x00007f8eb1be1cf6 g_log_default_handler (libglib-2.0.so.0)
                                                      #2  0x00007f8eb1bed71d g_logv (libglib-2.0.so.0)
                                                      #3  0x00007f8eb1be3f80 g_log (libglib-2.0.so.0)
                                                      #4  0x00007f8eb1d8e25f n/a (libgio-2.0.so.0)
                                                      #5  0x00007f8eb1d90893 g_settings_get_value (libgio-2.0.so.0)
                                                      #6  0x00007f8eb1d9093d g_settings_get_strv (libgio-2.0.so.0)
                                                      #7  0x00005625ea371193 n/a (gnome-flashback)
....
```

**Comment by gammons** [comment]
I was able to fix this by editing `/usr/share/glib-2.0/org.gnome.desktop.peripherals.gschema.xml` and duplicating the `output` key and renaming it to `display`.

So the whole `org.gnome.desktop.peripherals.touchscreen` section looks like this:

```
  <schema id="org.gnome.desktop.peripherals.touchscreen">
    <key name="output" type="as">
      <default>["", "", ""]</default>
      <summary>Touchscreen output mapping</summary>
      <description>EDID information of the output the touchscreen is mapped to. Must be in the format [vendor, product, serial]. ["","",""] relies on automatic mapping.</description>
    </key>
    <key name="display" type="as">
      <default>["", "", ""]</default>
      <summary>Touchscreen display mapping</summary>
      <description>EDID information of the output the touchscreen is mapped to. Must be in the format [vendor, product, serial]. ["","",""] relies on automatic mapping.</description>
    </key>
  </schema>
```

**Comment by muktupavels** [comment]
That is `gnome-flashback` bug! Please report issue here - https://gitlab.gnome.org/GNOME/gnome-flashback/issues. I knew that they changed `display` to `output`, but forgot to fix/change that.

**Comment by jcstr** [comment]
@muktupavels it seems that you push to the `gnome-flashback` repo, can you give us an update to get notified here? Thanks in advance. I haven't seen any issue open related with this yet, so I'll start the thread on [gitlab](https://gitlab.gnome.org/GNOME/gnome-flashback/issues/21).

**Comment by muktupavels** [comment]
Linked commit should fix this segfault. @gammons can you test it?

**Comment by jcstr** [comment]
Well, it's been days since GNOME updated `gnome-shell` and other related packages so, I haven't faced any of the issues mentioned here. 

Can confirm to close the issue?

**Comment by jcstr** [comment]
Closing due lack of activity.
