### ISSUE TITLE
PolicyKit auth dialogs do not appear

### ISSUE THREAD

**Issue by mmstick** [i3-gnome/i3-gnome#37]
Currently, policykit auth dialogs will fail to start

**Comment by jcstr** [comment]
Well, following #36 , it seems that this issue is related, and as were mentioned on that thread, is a gnome-flashback bug.

Let's see if GNOME devs give us an update on that if not, let's workaround anyway.

**Comment by muktupavels** [comment]
That dialog is provided by `gnome-flashback`, if it has crashed then you won't get it.

**Comment by jcstr** [comment]
Closing due lack of activity.
