### ISSUE TITLE
what components of gnome are required for this to work?

### ISSUE THREAD

**Issue by aspieln3r** [i3-gnome/i3-gnome#38]
on homepage, it lists gnome as a requirement, but gnome package group on arch will install a lot of bloat that comes with gnome de
To keep it minimal, what all packages are necessary for this setup to work, so that one can install only them with i3 instead of the whole group

**Comment by jcstr** [comment]
You can take a look at [i3-gnome/i3-gnome.session](https://github.com/i3-gnome/i3-gnome/blob/a99678270dd4e0af097e7c9cf5491b566fc5d06f/session/i3-gnome.session) and see explicity which components are required.

**Comment by aspieln3r** [comment]
how does gnome flashback fit in there?
settings daemon is there and also, i3-gnome
how is gnome-flashback invoked?

**Comment by jcstr** [comment]
You can read the wiki [Tips and tricks](https://github.com/i3-gnome/i3-gnome/wiki/Tips-&-Tricks#gnome-flashback) and [here](https://github.com/i3-gnome/i3-gnome/blob/master/session/gnome-session-i3).
