### ISSUE TITLE
Clipboard manager

### ISSUE THREAD

**Issue by jfernandz** [i3-gnome/i3-gnome#41]
I would like to clarify a few things about cliboard manager. I have issues to use `xfce4-screenshooter` along `parcellite`, I would say that before this last update you were using the gnome clipboard manager itself, but now with `parcellite` I cannot store my taken screenshot in the clipboard.

did you switch the clipboard manager in use after last update? 

I like `xfce4-screenshooter` because it does allow me to store them in multiple ways, clipboard, imgur, save them in my hdd, or open them with any kind of software; `gnome-screenshot -i` only allows me to save them in my hdd or into the clipboard. But the point is when I use `parceillite` as clipboard manager, `xfce4-screenshooter` does not show the "save to clipboard" option in the GUI when you take a screenshot; so I must use `xfce4-clipman` to get this option back. 

But I'd swear before last update I had this option, maybe you were using another different clipboard manager than `parcellite`?

**Comment by WyRe** [comment]
well, for a strange reason I had before (a few days ago) the "save to clipboard" option using `parcellite` (I thought I was using `gsd-clipboard` but I was not); I've found a proper workaround uninstalling `parcellite` ---which I don't know why it was starting when I had disabled it in i3 config--- and starting `xfce4-clipman` in my i3 config. 

Now I'm using `xfce4-clipman` and `xfce4-screenshooter` has the desired behavior. I don't know why before, `parcellite` was starting despite of its startup was disabled in my i3 config, though.

Thank you anyway. I'm going to close this issue in a few days if no one has any other suggestion.

![image](https://user-images.githubusercontent.com/4059108/65378319-ee332a80-dcb6-11e9-862e-0431c2412978.png)

**Comment by jcstr** [comment]
Well, to be honest I don't have suggestions to this, but this GNOME update chaged regarding `gnome-session` and so on so, it would make some stuff unusable. 

Let's keep this open in case someone has suggestions.

**Comment by muktupavels** [comment]
https://gitlab.gnome.org/GNOME/gnome-flashback/issues/19

**Comment by WyRe** [comment]
@muktupavels so has been `gsd-clipboard` removed from Gnome?

And by other hand ... Why is `parcellite` starting when it is not included in my i3 config?

**Comment by muktupavels** [comment]
No, not from GNOME... Clipboard manager is now part of [mutter](https://gitlab.gnome.org/GNOME/mutter/merge_requests/320). It is removed only from GNOME Settings Daemon or more precisely functionality was moved to mutter.

No idea what `parcellite` is...

**Comment by muktupavels** [comment]
Looks like parcellite installs autostart file - https://github.com/rickyrockrat/parcellite/blob/master/data/Makefile.am#L33. If you have `/etc/xdg/autostart/parcellite-startup.desktop`, then it is reason why it is autostarting.

**Comment by jcstr** [comment]
Well, it seems that this issue it's been open for a long time. Closing, but this can be re-open.
