### ISSUE TITLE
GNOME 3.34 update / gnome-control-c dumped core.

### ISSUE THREAD

**Issue by killajoe** [i3-gnome/i3-gnome#42]
`systemd-coredump[16659]: Process 16626 (gnome-control-c) of user 1001 dumped core.`

I can now start i3-gnome session but starting GCC fails with coredump.. 

* archlinux
* lightdm slick greeter

* same issue with GDM

**Comment by muktupavels** [comment]
Stacktrace might help...

**Comment by jcstr** [comment]
@killajoe These days the packages related to `gnome-session` , `gnome-shell `and so on have been updated, I suggest you to update the GNOME packages to the latest version.
Personally don't have any kind of issue with this.
