### ISSUE TITLE
gnome 3.34: gnome-power-manager removed

### ISSUE THREAD

**Issue by jantonioperez** [i3-gnome/i3-gnome#43]
As of gnome 3.34, gnome-power-manager is no longer it's own program and it's functionalist has been split up among the rest of gnome. 

This means that

`exec_always --no-startup-id gnome-power-manager`

from "Tips & Tricks" fails silently, and doesn't do anything

**Comment by jcstr** [comment]
Yeah, it looks like it's not working, but we have options for this case.
Personally i suggest you to install [TLP](https://wiki.archlinux.org/index.php/TLP) which is independent from the desktop environment, but anyways here's a list with more options to look forward:
https://wiki.archlinux.org/index.php/Power_management#Userspace_tools

**Comment by jantonioperez** [comment]
Thanks for the feedback! That looks good
