### ISSUE TITLE
Screen tearing in i3-gnome when using intel integrated graphics

### ISSUE THREAD

**Issue by jantonioperez** [i3-gnome/i3-gnome#45]
I experience severe screen tearing when using i3-gnome on Ubuntu 19.04 during normal activities (like scrolling on a webpage, or switching between workspaces). When I use the normal Ubuntu desktop environment, there's no screen tearing. 

Is there any way to fix this? For example, would it be possible to use gnome's compositor in i3-gnome? The underlying window manager is i3-gaps

**Comment by JockeTF** [comment]
You could try enabling `TearFree` in your drivers:

https://wiki.archlinux.org/index.php/Intel_graphics#Tearing

Alternatively, maybe using a compositor such as `Compton`.

**Comment by jcstr** [comment]
How helpful is `xrandr` for this case?

**Comment by jcstr** [comment]
closed due lack of activity.

**Comment by umoqnier** [comment]
I'm in the same situation here.

I have installed `picom` in my Arch and tried to enable `glx` backend in `picom.config` but it seems that don't work for me. Currently, I'm using a laptop too with an Intel integrated (this card by default) card and NVIDIA card (only for games and stuff). I would like to hear any suggestion :p
