### ISSUE TITLE
No systray

### ISSUE THREAD

**Issue by leucos** [i3-gnome/i3-gnome#46]
It seems than when using i3-gnome (gnome 3.34.1, i3 4.16.1) systray are in i3bar is not working anymore.

When running i3 only, everything is fine (caffeine-indicator, nm-applet, ...).

Any clue on what is going wrong ?

Thanks

**Comment by jcstr** [comment]
It would be really helpful if you show any kind of log or even a screenshot.

**Comment by jcstr** [comment]
closed due lack of activity
