### ISSUE TITLE
i3-gnome session locking with gdm

### ISSUE THREAD

**Issue by pinoaffe** [i3-gnome/i3-gnome#48]
This is more of a question than an issue: does i3-gnome support locking the X session with gdm and, if so, how would I do this?

**Comment by jcstr** [comment]
I just did a quick google-fu and you can apply this:

- https://askubuntu.com/questions/7776/how-do-i-lock-the-desktop-screen-via-command-line

As it seems, you have to install legacy software. You can give a try anyway.

**Comment by jcstr** [comment]
closed due lack of activity

**Comment by Tornado-Tim** [comment]
Yea I would like this too, the gnome-screensaver lock doesnt work. Trying to find a way to lock the session nicely.

**Comment by jcstr** [comment]
well, I have installed [betterlockscreen](https://github.com/pavanjadhaw/betterlockscreen), which is a cool approach for this.

**Comment by Tornado-Tim** [comment]
Ah got it working! Added gnome-screensaver to the i3 config file with `exec --no-startup-id /usr/bin/gnome-screensaver` and then send an appropriate dbus command to lock the session:
`dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock`

**Comment by edoardopigaiani** [comment]
> Ah got it working! Added gnome-screensaver to the i3 config file with `exec --no-startup-id /usr/bin/gnome-screensaver` and then send an appropriate dbus command to lock the session:
> `dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock`

Thanks, I finally got it working by adding it to the i3 config file as you suggested :)
You can also send an appropriate command to lock the session by typing `gnome-screensaver-command -l`, FYI :)

**Comment by jcstr** [comment]
I think that @Tornado-Tim's approach deserves to be on the wiki, I'll write it up!
Cheers!

**Comment by jcstr** [comment]
You can read it now here:
https://github.com/i3-gnome/i3-gnome/wiki/Tips-&-Tricks

**Comment by ctag** [comment]
gnome-screensaver appears to [be deprecated](https://wiki.gnome.org/action/show/Attic/GnomeScreensaver?action=show&redirect=Projects%2FGnomeScreensaver). Is there an up to date way to accomplish this?

**Comment by jakobwuhrer** [comment]
not that I know of, and gnome folks I talked to said they didn't really intend on supporting this type of a usecase

**Comment by ChuckBorris33** [comment]
New way to  accomplish this is `xdg-screensaver lock`
