### ISSUE TITLE
Segmentation fault opening gnome-control-center

### ISSUE THREAD

**Issue by WyRe** [i3-gnome/i3-gnome#49]
I'm getting a `segmentation fault (core dumped)` message when I try to open `gnome-control-center` binary.

**Comment by jcstr** [comment]
did you update to the latest versions of the GNOME packages? days ago have been updated.

**Comment by WyRe** [comment]
Of course, I'm in `3.34.1` version.

**Comment by jcstr** [comment]
This is weird, personally don't have any kind of issue, this is only related with GNOME control center?

**Comment by WyRe** [comment]
well, the strange thin is when I start `gnome` with `gdm` it does work as expected, but not in `i3-gnome`

Here the `gdb` output:

```
gdb gnome-control-center
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gnome-control-center...
(No debugging symbols found in gnome-control-center)
(gdb) r
Starting program: /usr/bin/gnome-control-center 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe9c02700 (LWP 15476)]
[New Thread 0x7fffe9401700 (LWP 15477)]
[New Thread 0x7fffe2100700 (LWP 15482)]
[New Thread 0x7fffe18ff700 (LWP 15483)]
[New Thread 0x7fffe1051700 (LWP 15485)]
[New Thread 0x7fffcffff700 (LWP 15499)]

Thread 1 "gnome-control-c" received signal SIGSEGV, Segmentation fault.
0x00005555556725c0 in cc_display_config_set_minimum_size ()
(gdb) c
Continuing.
Couldn't get registers: No existe el proceso.
Couldn't get registers: No existe el proceso.
(gdb) [Thread 0x7fffcffff700 (LWP 15499) exited]
[Thread 0x7fffe1051700 (LWP 15485) exited]
[Thread 0x7fffe18ff700 (LWP 15483) exited]
[Thread 0x7fffe2100700 (LWP 15482) exited]
[Thread 0x7fffe9401700 (LWP 15477) exited]
[Thread 0x7fffe9c02700 (LWP 15476) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
q
```

**Comment by WyRe** [comment]
> This is weird, personally don't have any kind of issue, this is only related with GNOME control center?

only with `gnome-control-center` right, other components like `gnome-calculator` or `gnome-calendar` works pretty fine. I cannot start `gnome-control-center` even from plain `i3` (instead of `i3-gnome`, I mean). I've also tried starting `i3-gnome` from `gdm` but still the same. 

How do you start `i3-gnome`, @jcstr ?

**Comment by muktupavels** [comment]
If you are not using mutter as window manager then it does not and can not provide that interface. You can try to use gnome-flashback...

**Comment by WyRe** [comment]
@muktupavels 

I'm using i3 as window manager, that's what is i3-gnome for! Ain't it?

**Comment by muktupavels** [comment]
gnome-flashback is not window manager! You need something that will provide mentioned interface... Even if it would not crash, you would not be able to configure your display/monitors.

Can you start GNOME Control Center with `gnome-control-center sound`?

**Comment by WyRe** [comment]
Yes, I know the window manager is `mutter`; but I didn't know that `gnome-flashback`  would provide that interface. 

You are right, I'm able to open `gnome-control-center` from sound config, and the issue is solved with `gnome-flashback`

Thank you so much, @muktupavels ;-)

**Comment by WyRe** [comment]
Anyway, I've noticed ... `gnome-flashback` crashes when I switch between or manage displays, it is working fine in your case? @muktupavels

**Comment by muktupavels** [comment]
Have not seen crashes. Can you provide steps that I could try to see if same thing works for me?

**Comment by WyRe** [comment]
Well @muktupavels, first of all you must

1. Add `exec --no-startup-id gnome-flashback` in i3 config (obviously)
2. Start `i3-gnome` by adding `exec i3-gnome` to .xinitrc and doing `startx` in a tty (I mean, I'm not using `gdm`)

but then

1. Take a laptop and plug in an extra display to hdmi output
2. start i3-gnome from the tty
3. (you could even to get a horizontal half split display even) but by default it will be always in `Join Displays` mode
4. Change to single display and choose HDMI output and apply
5. `gnome-flashback` crashes
4.

**Comment by muktupavels** [comment]
I am not using `i3`... Anyway, `gnome-flashback` crashing is upstream problem/bug. Can you report this crash here - https://gitlab.gnome.org/GNOME/gnome-flashback/issues. I will try to reproduce when I have more time. If you can, please attach also stacktrace.

**Comment by WyRe** [comment]
@muktupavels I'm not sure, because I've not tested `gnome-flashback` working in the gnome environment. I get also a crash when I start my `i3-gnome` with the secondary display plugged in and (since `gnome-control-center display` is loading by default in `Join Displays` mode) when I close the laptop lid to work only with HDMI output; then `gnome-flashback` crashes. Yes I know I must provide the stacktraces/backtraces. But I would like if you could certify this.

Anyway ... I don't like to much the integration between `gnome-control-center display` and `i3wm`.
___
Particularly `i3wm` working on multiple displays setup is not attractive to me. I think it is a complete mess, because by default you only can assign dynamically workspaces to displays (this is a complete mess because depends on which display you are, the next ws switch will be in there), the other possibility is fix workspaces for a particular display in the `i3` config file; but this is also a mess but more restrictive. 

I would like to get an extra space (the extra display) in each workspace and don't fight against which display is showing which workspace. But I guess this is a `i3wm` thing, I'm going to talk with `i3wm` people to see if I can get the behaviour desired.

I would like to be possible load by default `gnome-control-center display` in single display mode due this `i3` messy behaviour. Though when I change the showed display `gnome-flashback` crashes ...
___
**Another important** detail I've realized is ... `telegram` system tray icon disappears when I load `gnome-flashback`, that's **really bad.**

**Comment by muktupavels** [comment]
`gsettings set org.gnome.gnome-flashback status-notifier-watcher false` might help with tray icon.

**Comment by muktupavels** [comment]
I was able to reproduce crash on laptop, if it was same problem then fixed by https://gitlab.gnome.org/GNOME/gnome-flashback/commit/5e00c43dff14cb0c77498d39507e69176a377780.

**Comment by WyRe** [comment]
> `gsettings set org.gnome.gnome-flashback status-notifier-watcher false` might help with tray icon.

@muktupavels thank you for that appointment, I've found also the whole `gnome-flashback` config in `dconf-editor` and might be helpful for other things ---like disable `sound-applet` to use `pasystray` instead---

Also... when do you think your fix will be released? Which version I mean? Not for 3.34.0 I guess, but maybe the next, right?

**Comment by muktupavels** [comment]
Already done - https://gitlab.gnome.org/GNOME/gnome-flashback/commit/a845b1c7416a85a915935d889f855517eb359184.

**Comment by WyRe** [comment]
> Already done - https://gitlab.gnome.org/GNOME/gnome-flashback/commit/a845b1c7416a85a915935d889f855517eb359184.

Oh, yeah, but that's for `3.34.2`, I'm in `3.34.0` in Arch Linux, so I guess I must wait to devs update the package or maybe using `asp` I could repackage for the `3.34.2` tag

**Comment by jcstr** [comment]
is this issue fixed?

**Comment by WyRe** [comment]
I think it might be marked as closed, right.
