### ISSUE TITLE
unknown option --builtin

### ISSUE THREAD

**Issue by gfredericks** [i3-gnome/i3-gnome#50]
On Ubuntu 18.04, I experienced the symptom of logging in and being logged back out a second later. I found in the logs the message `unknown option --builtin`, and when I removed the `--builtin` arg from the pertinent file installed by this repo, things seemed to work okay.

I haven't investigated what that option means, I just wanted to log this here for posterity.

**Comment by Tommos0** [comment]
Running into the same issue. Related issue: https://github.com/i3-gnome/i3-gnome/issues/40 (this seems to be why it's added).

The --builtin option was added quite recently and first released with gnome-session 3.33.90. It seems it has something to do with systemd.

https://github.com/GNOME/gnome-session/commit/4d6ee3f55f1efa3dc63250c38f446f2cf6f6a5e2#diff-3484628c77c4018d02c40da5782c0aea

I'm gonna update to a more recent version of GNOME to fix this.

**Comment by jcstr** [comment]
It seems that ubuntu 18.04 uses GNOME 3.28, so we try to get i3-gnome usable as soon as GNOME gets updated. 

You can get understood why is `--builtin` used for this version GNOME by reading #40

**Comment by Tommos0** [comment]
A nice fix would be to check for the gnome version, and only use --builtin if the version is 3.33.90 or greater.

**Comment by mcabrams** [comment]
I am experiencing the same "symptom of logging in and being logged back out a second later," but that's even after using #53 updated branch.  Any tips for debugging @jcstr ?  I've tried updating gnome (currently 3.32, about to try 3.34), modifying `~/.config/i3/config`, and a bunch of other things.  i3 on it's own and regular ubuntu work fine, but using i3 + gnome immediately goes back to login screen.

**Comment by muktupavels** [comment]
Why #53 added `echo`? Perhaps that is the problem?

**Comment by mcabrams** [comment]
@muktupavels That appears to have been the culprit!

**Comment by jcstr** [comment]
@Tommos0 why did you added `echo` on the last command?

**Comment by jcstr** [comment]
Was about to draft a new release, but that just stop me doing it.

**Comment by Tommos0** [comment]
Oh big oops, that was a leftover from testing :fearful:

**Comment by mcabrams** [comment]
@jcstr I believe this issue can now be closed 👍

**Comment by gfredericks** [comment]
thanks everybody
