### ISSUE TITLE
Unresponsive after startup (but media keys work)

### ISSUE THREAD

**Issue by mcabrams** [i3-gnome/i3-gnome#51]
Hi,

I recently setup i3-gnome and after setting things up according to [tips & tricks](https://github.com/i3-gnome/i3-gnome/wiki/Tips-&-Tricks) I logged into i3 + GNOME and found that none of the keypresses that work in i3 worked in this environment.  I thought perhaps that the mod key had gotten reconfigured to the original, but even with using alt and every other thing I could think of, nothing responded.  I did notice that the media keys worked properly based on on screen feedback, but found it impossible to open a terminal, or exit.  Any advice?  Happy to provide any info that would be helpful. Thanks!

**Comment by mcabrams** [comment]
Update: I can tell all keypresses are being recognized, so I'm assuming it's some issue with i3 setup?  I am able to boot into regular i3 and open terminals fine.

**Comment by mcabrams** [comment]
Seems to be caused by using a fork of this repository by accident :man_facepalming: - that said, I'm now encountering #50

**Comment by mcabrams** [comment]
So, initially I thought this was from using fork, but after having `make uninstall` that version, and reinstalling this repo, and accounting for https://github.com/i3-gnome/i3-gnome/issues/50#issuecomment-550021807 , I am actually back with the same issue.

By process of elimination (commenting each line and restarting), I have determined that the cause of the issue seems to be including `exec --no-startup-id gnome-flashback` in my `~/.config/i3/config` file -- when it's commented things work properly (but no media key or background etc.), but when it's included things look good (media keys work, background for gnome shows), but I am unable to open a terminal, exit i3, etc.  I can see that all keypresses are being recognized by clicking "Show Keyboard Layout" in the bottom bar, but clearly it's not triggering i3.  Any tips for debugging or ideas of what may be going on?  Thanks.

**Comment by jcstr** [comment]
Well, there's a way to handle media keys but you have to do it with X window system:
- https://wiki.archlinux.org/index.php/extra_keyboard_keys
- https://wiki.archlinux.org/index.php/Extra_keyboard_keys
- https://wiki.archlinux.org/index.php/Xbindkeys

Anyways it is not a pretty succesful option but it's a start point

**Comment by jcstr** [comment]
It would be really useful if you show what version of GNOME have installed.
We focus on the last version released.

**Comment by mcabrams** [comment]
Based off `/usr/share/gnome/gnome-version.xml` I have 3.34.1 installed.  With `exec --no-startup-id gnome-flashback` included all the media keys work well, I'm just unable to do any of the normal i3 commands.

**Comment by mcabrams** [comment]
@jcstr Based off `/usr/share/gnome/gnome-version.xml` I have 3.34.1 installed.  With `exec --no-startup-id gnome-flashback` included all the media keys work well, I'm just unable to do any of the normal i3 commands.

**Comment by jcstr** [comment]
My guess, is this issue considered as fixed?

**Comment by mcabrams** [comment]
@jcstr it is not fixed.  As I mentioned in #54, this is a separate issue.  I think it might be a little confusing since there's been a few different problems, but to summarize, the issue and current state is this:

When the line `exec --no-startup-id gnome-flashback` is included in my `~/.config/i3/config` file, upon logging into i3 + GNOME I am unable to open a terminal ($mod+enter), unable to exit i3 ($mod+Shift+e), and basically the only thing I can do is a force restart via physical button.  I do have control over the mouse, and can click the keyboard layout icon in the status bar and have verified that my keypresses are in fact recognized (this includes all regular keys in addition to media keys).  Upon the line `exec --no-startup-id gnome-flashback` is included in my `~/.config/i3/config` file and rebooting into i3 + GNOME, things work properly, but there is obviously less GNOME integration.   

I'm very new to Linux so I'm not sure where to look to debug the issue - as I mentioned I'm on 3.34.1 of Gnome, so I don't think versioning is the issue here.

**Comment by mcabrams** [comment]
@jcstr I wouldn't be surprised if others encounter this, but it seems to be working for me now.  I'm not sure if it was because of a recent update, or just ensuring some applications are started up in workspaces, but things seem to be working properly now.
