### ISSUE TITLE
polkit-gnome and gnome power manager missing in Gnome 3.34

### ISSUE THREAD

**Issue by jantonioperez** [i3-gnome/i3-gnome#52]
In the **Tips and tricks** section of the wiki, i3-gnome recommends adding the following commands to the i3 config file:
```
exec_always --no-startup-id gnome-power-manager
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
```
In Ubuntu 19.10 / gnome 3.34, `gnome-power-manager` is not present, and neither is `/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1`.  The functionality for these programs was likely merged into other parts of gnome. 

Could you update the **Tips and tricks** section to explain how to properly use this functionality?

The response here (https://github.com/i3-gnome/i3-gnome/issues/43#issuecomment-538494653) discusses a good way to address the missing `gnome-power-manager` in **Tips and tricks**

**Comment by jcstr** [comment]
Good one, I forgot about that.

**Comment by sbonner0** [comment]
Sorry to comment on a closed ticket, but it seems that the **Tips and Tricks** section wasn't actually updated to reflect this. t!

Would it be possible get an updated Tips and Tricks incorporating best practices for using i3-gnome with gnome 3.36?
