### ISSUE TITLE
Windows are persistent when switching to blank workspace

### ISSUE THREAD

**Issue by msradam** [i3-gnome/i3-gnome#55]
Hi! I have really enjoyed using this so far, but have a pretty big QoL issue with windows not 'going away' when switching to a workspace, unless another application is opened on that workspace. 

For example:
Workspace 1:
![s1](https://user-images.githubusercontent.com/19861960/68536273-387f7200-031e-11ea-85a6-0ba64c38cd26.png)

Switching to Workspace 3:
![s2](https://user-images.githubusercontent.com/19861960/68536274-403f1680-031e-11ea-9fee-7aba18a8fcb0.png)

This occurs with all types of applications - the window itself remains visible when switching to a blank workspace, but cannot be interacted with since the application itself hasn't moved. This also results in the wallpaper being overwritten by a blank space when closing a window, or weird behavior where floating windows leave blank spaces:
![Screenshot from 2019-11-09 16-21-34](https://user-images.githubusercontent.com/19861960/68536309-bd6a8b80-031e-11ea-8fb8-ce1848d2610c.png)

System information:
Dell XPS 13 9370
Kernel: 5.3.8-arch1-1
i3-gnome 1:3.34.1-2 (installed from the AUR via yay)
GPU: Intel UHD Graphics 620 

This is a fresh installation with no other versions of i3 or Gnome being installed beforehand, and I'm using Gnome Flashback.

**Comment by jcstr** [comment]
Hi,
well, first things first. Do you have a graphic drive installed? the ones I have installed are `mesa` and `xf86-video-intel`.

That could be the reason of the problem.

Do you have only GNOME Flashback?

**Comment by msradam** [comment]
Hi,

Yes, I have both of those packages installed. This issue also does not show up in regular i3. I have both Gnome Flashback and regular Gnome that was installed by default with GDM, and I have this in my i3 config as the wiki suggested:

`exec --no-startup-id gnome-flashback`

I'd like to add on that this issue doesn't show up with my machine connected to external monitors and the lid down - everything looks fine on the external monitors. It seems like it may just be a rendering issue on my laptop screen specifically.

**Comment by jcstr** [comment]
Yeah, well, this the first time that this behavior is mentioned. Let me figure out what's going on and let's keep this issue open in case someone has a workaround.

**Comment by murtezayesil** [comment]
It may be due to how gnome auto discards empty workspaces.
Try forcing GNOME to have fixed number of workspaces using gnome-tweaks.

**Comment by muktupavels** [comment]
Do you have same problem without `gnome-flashback`? If yes, then it will be window manager problem.

**Comment by jcstr** [comment]
Closing due lack of activity.
