### ISSUE TITLE
Outdated path in wiki

### ISSUE THREAD

**Issue by mhsekhavat** [i3-gnome/i3-gnome#57]
Hi. In the recent gnome-shell versions, the path 

`/usr/lib/gnome-settings-daemon/gsd-xsettings`

which is referenced in [the wiki](https://github.com/i3-gnome/i3-gnome/wiki/Tips-&-Tricks#gnome-settings-daemon) doesn't exist any more. I found `/usr/lib/gsd-xsettings` exists in my current version.

**Comment by jcstr** [comment]
Thank you!
Updated now.

**Comment by wingpin6** [comment]
Currently on Ubuntu 20.04 LTS, and came across the wiki too. I don't see either:
`/usr/lib/gnome-settings-daemon/gsd-xsettings` or
`/usr/lib/gsd-xsettings`
in those directories.
But I do see `/usr/libexec/gsd-xsettings` in my list of running processes each startup without me explicitly calling it.

**Comment by jcstr** [comment]
@wingpin6 It looks like ubuntu handles a different approach for this, it's weird, but they make it work like that.
