### ISSUE TITLE
Gnome 3.36 spawns Desktop on startup

### ISSUE THREAD

**Issue by innerout** [i3-gnome/i3-gnome#58]
After user login nautilus spawns in the desktop folder. Is there a way to disable this behavior from happening?

**Comment by gammons** [comment]
I can repro this as well.  this is on an up-to-date arch install.

**Comment by muktupavels** [comment]
If you are using `gnome-flashback` then you can disable desktop with `gsettings set org.gnome.gnome-flashback desktop false`.

**Comment by innerout** [comment]
I can confirm @muktupavels solution works.

**Comment by WyRe** [comment]
@muktupavels Does this also mean I have to use feh to setup the wallpaper?

**Comment by muktupavels** [comment]
`gsettings set org.gnome.gnome-flashback root-background true` :)
