### ISSUE TITLE
Desktop instance when gnome-flashback is launched

### ISSUE THREAD

**Issue by WyRe** [i3-gnome/i3-gnome#60]
I've noticed recently (I guess after last `gnome-flashback` update) that in startups is spawning a desktop window.

![Captura de pantalla_2020-03-12_15-30-01](https://user-images.githubusercontent.com/4059108/76532626-2bfb5980-6477-11ea-880e-5e1d27262d1b.png)

Is there a way to launch `gnome-flashback` preventing this desktop instance? Maybe we could add a parameter to the i3 config directive? As you [point here](https://github.com/i3-gnome/i3-gnome/wiki/Tips-&-Tricks#gnome-flashback).

Is not a big problem because I can close that window and run the system normally.

![Captura de pantalla_2020-03-12_15-30-10](https://user-images.githubusercontent.com/4059108/76532658-37e71b80-6477-11ea-85a9-b3c1b101b163.png)

But I think it would be desirable to block it from the beginning.

**Comment by muktupavels** [comment]
https://github.com/i3-gnome/i3-gnome/issues/58

**Comment by WyRe** [comment]
@muktupavels sorry and thanks 👍
