### ISSUE TITLE
screen dims

### ISSUE THREAD

**Issue by roghnin** [i3-gnome/i3-gnome#61]
HI,

Thanks for your work! Most of the functionalities are working flawlessly except that the screen keeps dimming in like 30 seconds and I cannot turn it off or configure it anywhere. The option that is supposed to be in gnome-control-center is missing, and gsettings from terminal doesn't seem to work on this case.

Any quick fix? 

Thanks.

**Comment by muktupavels** [comment]
Are you using `gnome-flashback`?

Might be related to screensaver module, you can try to disable it `gsettings set org.gnome.gnome-flashback screensaver false`.

`gsettings get org.gnome.desktop.session idle-delay`?

**Comment by roghnin** [comment]
Well it is fixed when I uninstall another package called clight. This didn't happen when I'm using clight on its own though -- there might be some expected interactions between those two.

**Comment by roghnin** [comment]
Thanks for the help. I'm going to tune idle-delay and see if this operation works on its own.
