### ISSUE TITLE
dpi setting in xrandr

### ISSUE THREAD

**Issue by roghnin** [i3-gnome/i3-gnome#62]
Hi,

I've been scaling up i3 a bit with '--dpi' argument when calling xrandr, and I noticed that it won't work on i3-gnome. Any workaround?

**Comment by jcstr** [comment]
This is an specific case but I'd suggest to install `arandr` which can help you to manage all of your displays in a friendly way.

https://christian.amsuess.com/tools/arandr/

**Comment by mhcerri** [comment]
@roghnin, you can use a --scale value smaller than 1, for example:

```
xrandr --output <screen> --scale 0.5x0.5
```

That will make the interface twice bigger.

Another option would be to set a scale factor on gnome-control-center, in practice that should change the effective value of Xft.dpi in your Xresources.

**Comment by jcstr** [comment]
@mhcerri I think that your workaround will be added to the wiki, thanks!
