### ISSUE TITLE
Double lockscreen with gnome-screensaver

### ISSUE THREAD

**Issue by toketin** [i3-gnome/i3-gnome#63]
Hi, I've followed this wiki and added `gnome-screensaver` to the autostart application on i3 config, but I've noticed that now, when the pc goes on idle, I've to put twice the password on the lockscreen before having the system unclock. It seems a double lockscreen due to `gnome-screensaver`, because without it the system lock just once. 

I've noticed that even without adding `gnome-screensaver` to the autostart, if I lock the screen using `i3lock` and then the pc goes to idle, I've to unlock first `i3lock` and then to unlock `gnome` itself.

**Comment by muktupavels** [comment]
If you are using `gnome-flashback` and version is 3.36+ then `gnome-screensaver` is no longer needed - https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues/18.

You can disable builtin screensaver/lock screen if you want with:
`gsettings set org.gnome.gnome-flashback screensaver false`

**Comment by toketin** [comment]
Ok thanks Alberts, so the wiki should be updated. How could I do if I would like to rely just on `i3clock`? I mean to have the screen locked with it when the pc goes in idle under `i3-gnome`.

**Comment by muktupavels** [comment]
I don't know anything about `i3`! I just know that `gnome-flashback` might be used with it...

**Comment by krishicks** [comment]
@toketin 

> Ok thanks Alberts, so the wiki should be updated. How could I do if I would like to rely just on `i3lock`? I mean to have the screen locked with it when the pc goes in idle under `i3-gnome`.

I had the same issue as you, except I use xsecurelock. This is what I have in my ~/.config/i3/config:

```
exec --no-startup-id env XSECURELOCK_SAVER=/usr/lib/xscreensaver/cubicgrid xss-lock -l -- xsecurelock &
```

You'll probalby want something similar, but with i3lock.

**Comment by jcstr** [comment]
Closing due lack of activity.
