### ISSUE TITLE
Close Gnome-Flashback window

### ISSUE THREAD

**Issue by luxedo** [i3-gnome/i3-gnome#64]
First of all, thanks a lot for these scripts!

There's something I dislike in gnome-flashback and it's the fact that it opens a window with the desktop.
![Screenshot from 2020-04-10 00-32-34](https://user-images.githubusercontent.com/14118472/78960025-210e0600-7ac3-11ea-8639-1fd1f0a57e9a.png)

I know that even if I close this window the functionalities, like gnome-control-center, still works. So I wanted to close or hide this window somehow.

I looked in the usage for gnome-flashback and found no option to run it in the background:
```
Usage:
  gnome-flashback [OPTION…]

Help Options:
  -h, --help               Show help options
  --help-all               Show all help options
  --help-gtk               Show GTK+ Options

Application Options:
  -r, --replace            Replace a currently running application
  -v, --version            Print version and exit
  --display=DISPLAY        X display to use
```

And there's no issues section in the [gnome-flashback repo](https://github.com/GNOME/gnome-flashback).

Does anyone else think that this window is not useful? Is it possile to hide or close this window just after login?

**Comment by muktupavels** [comment]
https://github.com/i3-gnome/i3-gnome/issues/58

**Comment by luxedo** [comment]
Perfect! Thanks! 

I looked into the issues but wasn't thinking in the same keywords, I should have been more careful. It seems that this is a recurring issue, do you think it would be nice to have this in the [Tips & Tricks](https://github.com/i3-gnome/i3-gnome/wiki/Tips-&-Tricks)?
