### ISSUE TITLE
AUR i3-gnome error on upgrade

### ISSUE THREAD

**Issue by innerout** [i3-gnome/i3-gnome#65]
I am trying to upgrade i3-gnome from version 1:3.36.0-2 to 1:3.36.0-3 using the AUR package and it fails to remove `//usr/share/xsessions/i3-gnome.desktop`.
The command that the makepkg build fails is : 
`install: cannot remove '//usr/share/xsessions/i3-gnome.desktop': Permission denied`.

**Comment by jcstr** [comment]
Yes, it was a little misconception regarding the installation directory, specifically:
`//usr/share/xsessions/i3-gnome.desktop` 
if we look carefully the path is wrong, it should be:
`/usr/share/xsessions/i3-gnome.desktop`

The workaround here is to remove the conflicting files by hand.

Please, let me know if it worked for you.

**Comment by jcstr** [comment]
If we look at the PKGBUILD:
```
package() {
  cd "$pkgname-$pkgver"

  make install
}
```

The error was:
```
package() {
  cd "$pkgname-$pkgver"

  make DESTDIR="$pkgdir/" install
}
```

**Comment by jcstr** [comment]
Correct me if I'm wrong.

**Comment by jcstr** [comment]
There's no changes on i3-gnome, just on the PKGBUILD from AUR.

**Comment by GoliathLabs** [comment]
You are right. The maintainer used a wrong destination directory

**Comment by jcstr** [comment]
@GoliathLabs FYI I'm the maintainer of the AUR package as well.

I've realized this misconception due a fresh Arch Linux installation, just installed the AUR package and noticed the installation path as the mentioned.

That's why changed that in the PKGBUILD.

**Comment by GoliathLabs** [comment]
`make DESTDIR="$pkgdir" install` should be used then imho. Without the trailing slash

**Comment by GoliathLabs** [comment]
Or am I missing something

**Comment by jcstr** [comment]
@GoliathLabs Followed your suggestion. Updated now, it should work for everyone.

**Comment by jcstr** [comment]
This issue is considered as fixed. Closing now.
