### ISSUE TITLE
Unkillable Desktop window is created on launch 

### ISSUE THREAD

**Issue by sbonner0** [i3-gnome/i3-gnome#66]
Hey - thanks so much for all the work on i3-gnome, I really enjoy using it.

Recently I have been having some weird issues where upon launch, a 'Desktop' window is created which has icons for my home folder and recycle bin. This has been happening for some time, but recently I have been unable to kill this window!

Is there anyway to stop this window being spawned? I have no idea if it is being launched by i3-gnome itself, or something line gnome-flashback.

Below I have attached the portion of my i3 config which is launching the gnome related stuff. 

Any ideas would be most welcome :) 

```
# Gnome stuff
exec --no-startup-id /usr/lib/gsd-xsettings
exec --no-startup-id gnome-flashback
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec_always --no-startup-id gnome-power-manager
```

**Comment by muktupavels** [comment]
`gsettings set org.gnome.gnome-flashback desktop false`

**Comment by sbonner0** [comment]
Thanks that did indeed fix my issue! 

Are there any negatives to running gnome-flashback without a desktop? I notice it has removed the background desktop image for instance.

**Comment by muktupavels** [comment]
No. Background image can be enabled with `gsettings set org.gnome.gnome-flashback root-background true`.

**Comment by sbonner0** [comment]
That's got it - thank you!
