### ISSUE TITLE
Monitor hotplugging very unstable

### ISSUE THREAD

**Issue by Wilm0r** [i3-gnome/i3-gnome#70]
Although dual-screen works great when stable, it looks to me like there are two systems fighting each other sometimes when the display state changes (for example when I boot my laptop stand-alone and plug in my monitor later).

There will be a little bit of blinking etc, also in the i3bar area (from a workspace moving from/to the other monitor or so?) but the screen never really comes on. In my syslog I see a lot of churn about EDIDs and this:

```
/usr/libexec/gdm-x-session[25749]: [../../i3-wm-4.17.1/i3bar/src/xcb.c:985] ERROR: PropertyNotify received for unknown window 0040032b
```
Complete paste: https://p.gaa.st/view/19d0cde4

I've had this problem on two separate and unrelated (though both based on Debian testing) machines. On the first one I gave up and just went for single-screen (the instability eventually settles if you just disable the laptop screen and work on the external one only), and on the other one I've switched to plain i3 but now I miss a lot of i3-gnome goodness :-(

**Comment by jcstr** [comment]
Hey @Wilm0r! sorry for being late for this, but can you share us the version of both, GNOME and i3wm (i3-gaps), you're running?

**Comment by jeromenerf** [comment]
@Wilm0r from the logs, it seems like you have autorandr installed and managing monitors hotplugging. I guess it conflicts with gnome. Try uninstalling this package.

**Comment by jcstr** [comment]
Closing due lack of activity.
