### ISSUE TITLE
Missing icon tray 

### ISSUE THREAD

**Issue by nakobejo** [i3-gnome/i3-gnome#73]
i use Pop os 20.04 with gnome 3.36.3
when i use i3+gnome systemtray is broken, only few apps show up, discord telegram steam doesnt show up
i tried gsettings set org.gnome.gnome-flashback status-notifier-watcher false and it doesnt work at all
try i3 session and it works fine
anyway i use polybar

**Comment by nakobejo** [comment]
yes i do

**Comment by muktupavels** [comment]
Then it might be reason why you don't see tray icons. You most likely have `indicator-application-service` running, it also provides Status Notifier Watcher D-Bus service. If you don't need it, uninstall it.

**Comment by nakobejo** [comment]
thx for information i will disable that
