### ISSUE TITLE
wm agnostic implementation?

### ISSUE THREAD

**Issue by DavRack** [i3-gnome/i3-gnome#74]
Hi guys! Theres about 120 forks of this project, lots of them to include support for other wm like bspwm, awesome, sway etc.
So ... what have to be changed to make this project more wm agnostic? Im definitely looking to help at wherever I can.

**Comment by jcstr** [comment]
Hey @DavRack! The main functionality of i3-gnome is to bring some of the session components of GNOME to window managers, i3 as the majority.

The reason of 120 forks is that every window manager has its own personal customization, some users has different needs and they just work on its own.

Thanks for your interest! actually we need hands to help with the issues, and the maintenance of i3-gnome as well. Feel free to help us in something you see it needs to be worked :)  

Cheers!

**Comment by muktupavels** [comment]
Why do you want that? Would that solve something?

As you can see `i3` is used in file names. You would need to add some build script that generates files with correct names and content. For example if building with/for `bspwm` you would want to generate `bspwm-gnome.session` with `i3-gnome` replaced with `bspwm-gnome` in it.
