### ISSUE TITLE
Will this work with i3-gaps?

### ISSUE THREAD

**Issue by ycooreman** [i3-gnome/i3-gnome#75]
I've been using Regolith, which is pretty awesome for anyone who wants i3 with the advantages og Gnome, but it uses Ubuntu 20.04 as a base and I prefer Arch. So I was thinking about doing my own i3/Gnome combo when I stumbled upon this great Github project. 

Will it work with i3-gaps, and if so, does it need any special tweaking or preparation?

Cheers

**Comment by jcstr** [comment]
Yes! it should work flawlessly with i3-gaps. No need for something special, if you're on Arch I'd suggest to install the AUR package.

**Comment by ycooreman** [comment]
Brilliant. I'll post an update about how I got on
Many thanks!

**Comment by ycooreman** [comment]
Seems quite nice so far.
One bit of weirdness..

The first workspace seems to spawn the desktop as a window (showing some desktop icons and everything) so opening a app in the first workspace then opens that new app in the second half of the screen. It's as if it has taken the Gnome desktop icons stuff and is serving that as window.

I'm not sure what's causing that. Might be be gnome flashback

**Comment by martindoublem** [comment]
Also interested in this. We could make a desktop with settings à la regolith too if you are interested.

**Comment by jcstr** [comment]
Hey @martindoublem! thanks for your interest, sadly I don't have enough time to work for it :(

**Comment by martindoublem** [comment]
Works great on arch by the way!
