### ISSUE TITLE
1st workspace showing Gnome desktop as window

### ISSUE THREAD

**Issue by ycooreman** [i3-gnome/i3-gnome#76]
Seems quite nice so far.
One bit of weirdness..

The first workspace seems to spawn the Gnome desktop as a window (showing some desktop icons and everything) so opening an app in the first workspace then opens that new app in the second half of the screen. It really is as if it has taken the Gnome desktop and is serving that as window. I can even right-click on it to get the Gnome desktop context menu.

I'm not sure what's causing that. Might be be gnome flashback

**Comment by muktupavels** [comment]
Yes, it can be `gnome-flashback`! Try to disable desktop - `gsettings set org.gnome.gnome-flashback desktop false`.

**Comment by ycooreman** [comment]
Bingo. That fixed it

**Comment by aliceriot** [comment]
@jcstr would you consider adding this to the 'tips and tricks' page in the wiki? could save people like me (who just ran into this issue!) a little time if this fix were mentioned here: https://github.com/i3-gnome/i3-gnome/wiki/Tips-&-Tricks#gnome-flashback

**Comment by jcstr** [comment]
@aliceriot for sure! I'll add this to the wiki!

**Comment by jcstr** [comment]
@aliceriot ready! take a look! https://github.com/i3-gnome/i3-gnome/wiki/Tips-&-Tricks#1st-workspace-showing-gnome-desktop-as-window
