### ISSUE TITLE
Saving workspace layouts?

### ISSUE THREAD

**Issue by isinaltinkaya** [i3-gnome/i3-gnome#80]
Hi, thanks for i3-gnome. I have been using i3wm for years and had to switch to Ubuntu 20 from Manjaro Architect as it was getting very buggy and hard to maintain using ThinkPad x1 Carbon Gen 8. So far i3-gnome is working just fine.

Do you know any way to save workspace layouts for specific projects and restore them when I open the project again? Is this something that can be integrated into i3-gnome?

Thanks!

**Comment by mtweg** [comment]
I think you can make that work in i3 directly:
[take a look](https://i3wm.org/docs/layout-saving.html)
hth
cheers!
