### ISSUE TITLE
Compositing

### ISSUE THREAD

**Issue by hasmaneuroda** [i3-gnome/i3-gnome#81]
I want to use the native gnome/budgie compositor but I do not know what it's calledl
At the moment I installed compton to solve this but I think that normally should be unnecessary.

**Comment by muktupavels** [comment]
You can not do that (if I understand you correctly)... If you want GNOME compositor you have to use gnome-shell / mutter!

**Comment by hasmaneuroda** [comment]
Okay, I see. 
I was thinking if gnome is using a compositor I should've be able to use it in i3, too. Like I can use the gnome-screensaver for example.

**Comment by muktupavels** [comment]
There is no separate compositor. Mutter is both window manager and compositor.

**Comment by hasmaneuroda** [comment]
Thanks for the information, I reall didn't know that.
