### ISSUE TITLE
i3 + GNOME session won't start unless i log into GNOME session first

### ISSUE THREAD

**Issue by Im-Beast** [i3-gnome/i3-gnome#93]
**Describe the bug**
`i3 + GNOME` session won't start unless I log into `GNOME` session, then logout from it and log into `i3 + GNOME` session.

**To Reproduce**
1. Go to login screen
2. Try to log to `i3 + GNOME` session
3. Get redirected back to greeter

**Expected behavior**
Logging into `i3 + GNOME` session without needing to first log into `GNOME` session

**Desktop (please complete the following information):**
 - OS: Arch Linux (kernel 5.14.16-arch1-1)
 - Gnome Version: 41.1-1

**Comment by jcstr** [comment]
Hello @Im-Beast! 

Looking forward to find the solution on this. Did you already solved it?

Thanks in advance.

**Comment by Im-Beast** [comment]
Hi!
It's actually odd, it fixed itself after some update, not sure what's caused the problem nor what fixed it tho.

**Comment by jcstr** [comment]
Awesome! Glad to know that. 

Feel free to [read the wiki to find some trouble shootings](https://github.com/i3-gnome/i3-gnome/wiki) that we already fixed. i3-gnome break with each update from time to time and the wiki have helped a lot of users.

Cheers!

**Comment by j1cs** [comment]
I'm fascinating the same issue but i couldn't find any logs to have a clue ...

**Comment by j1cs** [comment]
the symptoms are as follows:
i can't login with i3-gnome.desktop nor with gnome-flashback-metacity.desktop.

if I log in to gnome.desktop (from wayland-session of course) and log back in to i3-gnome.desktop everything works fine

I got the logs of the failed cases, redirecting the output to a file. 
[i3-gnome log](https://glats.me/uploads/i3-gnome.log) and [gnome flashback log](https://glats.me/uploads/gnome.log)

the only pattern I find is "Cannot open display:".
I don't know where else to look.

**Comment by jcstr** [comment]
Hi @j1cs! I re-opened the issue, let's find out. If you can provide us any log or any related information it would be awesome.

**Comment by j1cs** [comment]
> Hi @j1cs! I re-opened the issue, let's find out. If you can provide us any log or any related information it would be awesome.

great. thank you.

here is i found out:


> the symptoms are as follows: i can't login with i3-gnome.desktop nor with gnome-flashback-metacity.desktop.
> 
> if I log in to i3.desktop (i3-gaps) and log back in to i3-gnome.desktop everything works fine
> 
> I got the logs of the failed cases, redirecting the output to a file. [i3-gnome log](https://glats.me/uploads/i3-gnome.log) and [gnome flashback log](https://glats.me/uploads/gnome.log)
> 
> the only pattern I find is "Cannot open display:". I don't know where else to look.

**Comment by jcstr** [comment]
Hi @muktupavels, I'm looking for useful resources and I'd to ask you for your help here. Seems like the issue it's between GNOME and GNOME Flashback. TBH I don't know where to start.

Thanks so much in advance.

@j1cs If you can share us which Linux distro are using would be helpful as well. Thanks in advance.

**Comment by jcstr** [comment]
@j1cs no worries! Glad that everything it's ok now.

Cheers!

**Comment by muktupavels** [comment]
No idea what could have caused this issue.
