### ISSUE TITLE
I want to help on this project

### ISSUE THREAD

**Issue by livegrenier** [i3-gnome/i3-gnome#97]
Hello,

I made a spec file that works if you want an RPM build process (see below), I have added it as part of my i3-desktop copr repo: https://copr.fedorainfracloud.org/coprs/livegrenier/i3-desktop/

Feel free to use the spec file below to get an RPM, or if you prefer I can make another copr repo and maintain it for you.

Let me know if i can help you in any way :) 

```
%define debug_package %nil

Name:		i3-gnome
Version:	40.4
Release:	1%{?dist}
Summary:	Use i3 with GNOME Session integration.

License:	MIT
URL:		https://github.com/i3-gnome/%{name}
Source0:	%{url}/archive/refs/tags/%{version}.tar.gz

BuildRequires:  gcc
BuildRequires:  make

Requires:	i3
Requires:	gnome-session
Requires:	gnome-settings-daemon

%description
Allows you to use i3wm with GNOME 3 Session infrastructure

%prep
%setup

%build
%make_build
%install
%make_install

%files
/usr/bin/i3-gnome
/usr/share/applications/i3-gnome.desktop
/usr/share/gnome-session/sessions/i3-gnome.session
/usr/share/xsessions/i3-gnome.desktop
/usr/bin/gnome-session-i3

%doc README.md
%license LICENSE

%changelog
* Sat Feb 19 2022 dave <livegrenier@gmail.com> - 40.4
- Initial version

```

**Comment by jcstr** [comment]
Hey @livegrenier, thanks for your interest on the project.

Seems like you have been working on your side. I'm not a Fedora user, but it's great to have more options available for everyone.

I'd like to welcome to the project! Check your inbox to see the invitation!

![image](https://user-images.githubusercontent.com/11054850/155019944-6caaa601-ca7d-465b-8adb-eec77ad3e4df.png)
